/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as Junin1RouteImport } from './routes/junin1'
import { Route as Junin2RouteImport } from './routes/junin2'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as SiscRouteImport } from './routes/sisc'
import { Route as Upsell1RouteImport } from './routes/upsell-1'
import { Route as Upsell2RouteImport } from './routes/upsell-2'
import { Route as Upsell3RouteImport } from './routes/upsell-3'
import { Route as Upsell4RouteImport } from './routes/upsell-4'
import { Route as Upsell5RouteImport } from './routes/upsell-5'
import { Route as ApiPublicFreepayRouteImport } from './routes/api/public/freepay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const Junin1Route = Junin1RouteImport.update({
  id: '/junin1',
  path: '/junin1',
  getParentRoute: () => rootRouteImport,
} as any)
const Junin2Route = Junin2RouteImport.update({
  id: '/junin2',
  path: '/junin2',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const SiscRoute = SiscRouteImport.update({
  id: '/sisc',
  path: '/sisc',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell1Route = Upsell1RouteImport.update({
  id: '/upsell-1',
  path: '/upsell-1',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell2Route = Upsell2RouteImport.update({
  id: '/upsell-2',
  path: '/upsell-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell3Route = Upsell3RouteImport.update({
  id: '/upsell-3',
  path: '/upsell-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell4Route = Upsell4RouteImport.update({
  id: '/upsell-4',
  path: '/upsell-4',
  getParentRoute: () => rootRouteImport,
} as any)
const Upsell5Route = Upsell5RouteImport.update({
  id: '/upsell-5',
  path: '/upsell-5',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFreepayRoute = ApiPublicFreepayRouteImport.update({
  id: '/api/public/freepay',
  path: '/api/public/freepay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/junin1': typeof Junin1Route
  '/junin2': typeof Junin2Route
  '/obrigado': typeof ObrigadoRoute
  '/registro': typeof RegistroRoute
  '/sisc': typeof SiscRoute
  '/upsell-1': typeof Upsell1Route
  '/upsell-2': typeof Upsell2Route
  '/upsell-3': typeof Upsell3Route
  '/upsell-4': typeof Upsell4Route
  '/upsell-5': typeof Upsell5Route
  '/api/public/freepay': typeof ApiPublicFreepayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/junin1': typeof Junin1Route
  '/junin2': typeof Junin2Route
  '/obrigado': typeof ObrigadoRoute
  '/registro': typeof RegistroRoute
  '/sisc': typeof SiscRoute
  '/upsell-1': typeof Upsell1Route
  '/upsell-2': typeof Upsell2Route
  '/upsell-3': typeof Upsell3Route
  '/upsell-4': typeof Upsell4Route
  '/upsell-5': typeof Upsell5Route
  '/api/public/freepay': typeof ApiPublicFreepayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/junin1': typeof Junin1Route
  '/junin2': typeof Junin2Route
  '/obrigado': typeof ObrigadoRoute
  '/registro': typeof RegistroRoute
  '/sisc': typeof SiscRoute
  '/upsell-1': typeof Upsell1Route
  '/upsell-2': typeof Upsell2Route
  '/upsell-3': typeof Upsell3Route
  '/upsell-4': typeof Upsell4Route
  '/upsell-5': typeof Upsell5Route
  '/api/public/freepay': typeof ApiPublicFreepayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/junin1'
    | '/junin2'
    | '/obrigado'
    | '/registro'
    | '/sisc'
    | '/upsell-1'
    | '/upsell-2'
    | '/upsell-3'
    | '/upsell-4'
    | '/upsell-5'
    | '/api/public/freepay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/junin1'
    | '/junin2'
    | '/obrigado'
    | '/registro'
    | '/sisc'
    | '/upsell-1'
    | '/upsell-2'
    | '/upsell-3'
    | '/upsell-4'
    | '/upsell-5'
    | '/api/public/freepay'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/junin1'
    | '/junin2'
    | '/obrigado'
    | '/registro'
    | '/sisc'
    | '/upsell-1'
    | '/upsell-2'
    | '/upsell-3'
    | '/upsell-4'
    | '/upsell-5'
    | '/api/public/freepay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  Junin1Route: typeof Junin1Route
  Junin2Route: typeof Junin2Route
  ObrigadoRoute: typeof ObrigadoRoute
  RegistroRoute: typeof RegistroRoute
  SiscRoute: typeof SiscRoute
  Upsell1Route: typeof Upsell1Route
  Upsell2Route: typeof Upsell2Route
  Upsell3Route: typeof Upsell3Route
  Upsell4Route: typeof Upsell4Route
  Upsell5Route: typeof Upsell5Route
  ApiPublicFreepayRoute: typeof ApiPublicFreepayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junin1': {
      id: '/junin1'
      path: '/junin1'
      fullPath: '/junin1'
      preLoaderRoute: typeof Junin1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junin2': {
      id: '/junin2'
      path: '/junin2'
      fullPath: '/junin2'
      preLoaderRoute: typeof Junin2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sisc': {
      id: '/sisc'
      path: '/sisc'
      fullPath: '/sisc'
      preLoaderRoute: typeof SiscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-1': {
      id: '/upsell-1'
      path: '/upsell-1'
      fullPath: '/upsell-1'
      preLoaderRoute: typeof Upsell1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-2': {
      id: '/upsell-2'
      path: '/upsell-2'
      fullPath: '/upsell-2'
      preLoaderRoute: typeof Upsell2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-3': {
      id: '/upsell-3'
      path: '/upsell-3'
      fullPath: '/upsell-3'
      preLoaderRoute: typeof Upsell3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-4': {
      id: '/upsell-4'
      path: '/upsell-4'
      fullPath: '/upsell-4'
      preLoaderRoute: typeof Upsell4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-5': {
      id: '/upsell-5'
      path: '/upsell-5'
      fullPath: '/upsell-5'
      preLoaderRoute: typeof Upsell5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/freepay': {
      id: '/api/public/freepay'
      path: '/api/public/freepay'
      fullPath: '/api/public/freepay'
      preLoaderRoute: typeof ApiPublicFreepayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  Junin1Route: Junin1Route,
  Junin2Route: Junin2Route,
  ObrigadoRoute: ObrigadoRoute,
  RegistroRoute: RegistroRoute,
  SiscRoute: SiscRoute,
  Upsell1Route: Upsell1Route,
  Upsell2Route: Upsell2Route,
  Upsell3Route: Upsell3Route,
  Upsell4Route: Upsell4Route,
  Upsell5Route: Upsell5Route,
  ApiPublicFreepayRoute: ApiPublicFreepayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
